name: GamesInTheBox
version: '${project.version}'
main: me.hsgamer.gamesinthebox.GamesInTheBox
api-version: 1.13
authors: [ HSGamer ]
description: Minigames in one region
softdepend:
  - HolographicDisplays
  - DecentHolograms
  - PlaceholderAPI
